name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile handout
        uses: xu-cheng/latex-action@v2
        with:
          root_file: handout.tex
      - name: Compile presentation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: presentation.tex
      - run: |
          sudo mv out/notes.pdf notes.pdf
          sudo mv out/presentation.pdf presentation.pdf
      - name: Upload LaTeX document
        uses: actions/upload-artifact@v3
        with: 
          name: PDF
          path: |
            handout.pdf
            presentation.pdf