on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile handout
        uses: xu-cheng/latex-action@v2
        with:
          root_file: handout.tex
      - name: Compile presentation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: presentation.tex
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          body: |
            This is a nightly release of mamba.
          files: |
            artifact.txt
          repository: pavelzw/micromamba-nightlies
          token: ${{ secrets.MICROMAMBA_NIGHTLIES_TOKEN }}
          tag_name: 'sha-${{ github.sha }}'
      - name: Upload handout
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/handout.pdf
          asset_name: handout.pdf
          asset_content_type: application/pdf
      - name: Upload presentation
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/presentation.pdf
          asset_name: presentation.pdf
          asset_content_type: application/pdf